name: Mintlify Deployment

on:
  deployment_status:

jobs:
  mintlify-deployment:
    timeout-minutes: 30
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy Mintlify
        run: |
          curl --request POST \
          --url https://api.mintlify.com/v1/project/update/650fb8a002108e0f4f80a0b9 \
          --header 'Authorization: Bearer ${{secrets.MINTLIFY_API_KEY}}'
